### ISSUE TITLE
Deprecation warning with Symfony 4.3

### ISSUE THREAD

**Issue by damienalexandre** [redirectionio/proxy-symfony#3]
Two deprecation warning are shown with SF 4.3:

## Missing root node

> A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.
```
  /var/www/vendor/symfony/config/Definition/Builder/TreeBuilder.php:30
  /var/www/vendor/redirectionio/proxy-symfony/DependencyInjection/Configuration.php:18
```

## Root method

> The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "redirection_io" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.
```
  /var/www/vendor/symfony/config/Definition/Builder/TreeBuilder.php:52
  /var/www/vendor/redirectionio/proxy-symfony/DependencyInjection/Configuration.php:19
```

**Comment by qboot** [comment]
Fixed in #4
