### ISSUE TITLE
Publish a release with the Persist Flag

### ISSUE THREAD

**Issue by damienalexandre** [redirectionio/proxy-symfony#6]
This commit https://github.com/redirectionio/proxy-symfony/commit/19a9875d40f24d8e1f5a9c280afb81a60f3d2b84 introduce a parameter I need on a project.

But there is no release with it.

It's the same on the SDK: https://github.com/redirectionio/proxy-sdk-php/commit/64c278f1da4356c6d5425f254b79cee0b848460b

I use this option in production already and it works.

```
        "redirectionio/proxy-sdk": "dev-public/make-persist-configurable as 0.3.1",
        "redirectionio/proxy-symfony": "dev-public/make-persist-configurable as 0.2.1",
```

**Comment by lyrixx** [comment]
Thanks for the notification.

Here you go

* https://github.com/redirectionio/proxy-symfony/releases/tag/v0.3.0
* https://github.com/redirectionio/proxy-sdk-php/releases/tag/v0.4.0

**Comment by damienalexandre** [comment]
Thanks!

**Comment by damienalexandre** [comment]
It does not work.

```
  Problem 1
    - Installation request for redirectionio/proxy-symfony ^0.3 -> satisfiable by redirectionio/proxy-symfony[v0.3.0].
    - redirectionio/proxy-symfony v0.3.0 requires redirectionio/proxy-sdk 0.3.* -> satisfiable by redirectionio/proxy-sdk[v0.3.0, v0.3.1] but these conflict with your requirements or minimum-stability.
```

https://packagist.org/packages/redirectionio/proxy-symfony needs sdk 0.3.* only.

**Comment by lyrixx** [comment]
Can you try again? It should be OK

**Comment by damienalexandre** [comment]
Thanks it worked with:

```
        "redirectionio/proxy-symfony": "^0.3.0",
        "redirectionio/proxy-sdk": "^0.4.0"
```

**Comment by lyrixx** [comment]
@damienalexandre For you information only 
```json
        "redirectionio/proxy-symfony": "^0.3.0",
```
should be enough
